import SwiftUI

extension Theme {

    // ──────────────────────────────────────────────
    // MARK: - Dark Themes
    // ──────────────────────────────────────────────

    // MARK: Midnight (GitHub Dark)
    static let midnight = Theme(
        id: "midnight",
        name: "Midnight",
        icon: "moon.stars.fill",
        sidebarBackground: Color(hex: "#010409"),
        listBackground: Color(hex: "#0D1117"),
        detailBackground: Color(hex: "#0D1117"),
        cardBackground: Color(hex: "#161B22"),
        selectedCardBackground: Color(hex: "#1F2937"),
        hoverBackground: Color(hex: "#161B22"),
        searchBarBackground: Color(hex: "#161B22"),
        accentPrimary: Color(hex: "#58A6FF"),
        accentSecondary: Color(hex: "#3FB950"),
        textPrimary: Color(hex: "#E6EDF3"),
        textSecondary: Color(hex: "#8B949E"),
        textTertiary: Color(hex: "#484F58"),
        textInverse: Color(hex: "#FFFFFF"),
        border: Color(hex: "#30363D"),
        divider: Color(hex: "#21262D"),
        unreadIndicator: Color(hex: "#58A6FF"),
        attachmentBackground: Color(hex: "#161B22"),
        avatarRing: Color(hex: "#58A6FF"),
        destructive: Color(hex: "#F85149"),
        buttonPrimary: Color(hex: "#238636"),
        buttonSecondary: Color(hex: "#21262D"),
        inputBackground: Color(hex: "#0D1117"),
        tagBackground: Color(hex: "#1F2937")
    )

    // MARK: Ocean – poussé vers le teal pour se distinguer de Midnight
    static let ocean = Theme(
        id: "ocean",
        name: "Ocean",
        icon: "water.waves",
        sidebarBackground: Color(hex: "#061A1E"),
        listBackground: Color(hex: "#0A2229"),
        detailBackground: Color(hex: "#0E2A32"),
        cardBackground: Color(hex: "#143640"),
        selectedCardBackground: Color(hex: "#1A424E"),
        hoverBackground: Color(hex: "#143640"),
        searchBarBackground: Color(hex: "#143640"),
        accentPrimary: Color(hex: "#22D3EE"),
        accentSecondary: Color(hex: "#34D399"),
        textPrimary: Color(hex: "#F0FDFA"),
        textSecondary: Color(hex: "#7DAFB8"),
        textTertiary: Color(hex: "#4A7A84"),
        textInverse: Color(hex: "#FFFFFF"),
        border: Color(hex: "#1C4D5A"),
        divider: Color(hex: "#143640"),
        unreadIndicator: Color(hex: "#22D3EE"),
        attachmentBackground: Color(hex: "#143640"),
        avatarRing: Color(hex: "#22D3EE"),
        destructive: Color(hex: "#FF453A"),
        buttonPrimary: Color(hex: "#0891B2"),
        buttonSecondary: Color(hex: "#1C4D5A"),
        inputBackground: Color(hex: "#0A2229"),
        tagBackground: Color(hex: "#1A424E")
    )

    // MARK: Serif
    static let serif = Theme(
        id: "serif",
        name: "Serif",
        icon: "book.fill",
        sidebarBackground: Color(hex: "#181C26"),
        listBackground: Color(hex: "#1C2230"),
        detailBackground: Color(hex: "#202636"),
        cardBackground: Color(hex: "#272D3C"),
        selectedCardBackground: Color(hex: "#303848"),
        hoverBackground: Color(hex: "#2A3040"),
        searchBarBackground: Color(hex: "#272D3C"),
        accentPrimary: Color(hex: "#E8736D"),
        accentSecondary: Color(hex: "#6E88E0"),
        textPrimary: Color(hex: "#E6E2EA"),
        textSecondary: Color(hex: "#8A8694"),
        textTertiary: Color(hex: "#56525E"),
        textInverse: Color(hex: "#1C2230"),
        border: Color(hex: "#343A4A"),
        divider: Color(hex: "#282E3C"),
        unreadIndicator: Color(hex: "#6E88E0"),
        attachmentBackground: Color(hex: "#272D3C"),
        avatarRing: Color(hex: "#E8736D"),
        destructive: Color(hex: "#E8736D"),
        buttonPrimary: Color(hex: "#6E88E0"),
        buttonSecondary: Color(hex: "#343A4A"),
        inputBackground: Color(hex: "#1C2230"),
        tagBackground: Color(hex: "#303848")
    )

    // MARK: Nord – textSecondary assombri pour mieux hiérarchiser
    static let nord = Theme(
        id: "nord",
        name: "Nord",
        icon: "snowflake",
        sidebarBackground: Color(hex: "#2E3440"),
        listBackground: Color(hex: "#3B4252"),
        detailBackground: Color(hex: "#434C5E"),
        cardBackground: Color(hex: "#4C566A"),
        selectedCardBackground: Color(hex: "#5E6A82"),
        hoverBackground: Color(hex: "#4C566A"),
        searchBarBackground: Color(hex: "#4C566A"),
        accentPrimary: Color(hex: "#88C0D0"),
        accentSecondary: Color(hex: "#A3BE8C"),
        textPrimary: Color(hex: "#ECEFF4"),
        textSecondary: Color(hex: "#B0B8C8"),
        textTertiary: Color(hex: "#7B849A"),
        textInverse: Color(hex: "#2E3440"),
        border: Color(hex: "#5E6A82"),
        divider: Color(hex: "#4C566A"),
        unreadIndicator: Color(hex: "#88C0D0"),
        attachmentBackground: Color(hex: "#4C566A"),
        avatarRing: Color(hex: "#88C0D0"),
        destructive: Color(hex: "#BF616A"),
        buttonPrimary: Color(hex: "#88C0D0"),
        buttonSecondary: Color(hex: "#5E6A82"),
        inputBackground: Color(hex: "#4C566A"),
        tagBackground: Color(hex: "#5E6A82")
    )

    // MARK: Rosé – card légèrement relevé pour le contraste
    static let rose = Theme(
        id: "rose",
        name: "Rosé",
        icon: "heart.fill",
        sidebarBackground: Color(hex: "#1A1118"),
        listBackground: Color(hex: "#211620"),
        detailBackground: Color(hex: "#281B26"),
        cardBackground: Color(hex: "#352432"),
        selectedCardBackground: Color(hex: "#42303E"),
        hoverBackground: Color(hex: "#352432"),
        searchBarBackground: Color(hex: "#352432"),
        accentPrimary: Color(hex: "#E8A0BF"),
        accentSecondary: Color(hex: "#BA68C8"),
        textPrimary: Color(hex: "#F8E8F0"),
        textSecondary: Color(hex: "#B89AAE"),
        textTertiary: Color(hex: "#7A5A6E"),
        textInverse: Color(hex: "#1A1118"),
        border: Color(hex: "#42303E"),
        divider: Color(hex: "#352432"),
        unreadIndicator: Color(hex: "#E8A0BF"),
        attachmentBackground: Color(hex: "#352432"),
        avatarRing: Color(hex: "#E8A0BF"),
        destructive: Color(hex: "#FF6B8A"),
        buttonPrimary: Color(hex: "#E8A0BF"),
        buttonSecondary: Color(hex: "#42303E"),
        inputBackground: Color(hex: "#2D1E2B"),
        tagBackground: Color(hex: "#42303E")
    )

    // MARK: Solarized Dark
    static let solarizedDark = Theme(
        id: "solarized-dark",
        name: "Solarized",
        icon: "sun.haze.fill",
        sidebarBackground: Color(hex: "#002129"),
        listBackground: Color(hex: "#002B36"),
        detailBackground: Color(hex: "#073642"),
        cardBackground: Color(hex: "#0A4050"),
        selectedCardBackground: Color(hex: "#114B5C"),
        hoverBackground: Color(hex: "#0A4050"),
        searchBarBackground: Color(hex: "#0A4050"),
        accentPrimary: Color(hex: "#268BD2"),
        accentSecondary: Color(hex: "#2AA198"),
        textPrimary: Color(hex: "#FDF6E3"),
        textSecondary: Color(hex: "#93A1A1"),
        textTertiary: Color(hex: "#657B83"),
        textInverse: Color(hex: "#002B36"),
        border: Color(hex: "#114B5C"),
        divider: Color(hex: "#073642"),
        unreadIndicator: Color(hex: "#268BD2"),
        attachmentBackground: Color(hex: "#0A4050"),
        avatarRing: Color(hex: "#268BD2"),
        destructive: Color(hex: "#DC322F"),
        buttonPrimary: Color(hex: "#268BD2"),
        buttonSecondary: Color(hex: "#114B5C"),
        inputBackground: Color(hex: "#002B36"),
        tagBackground: Color(hex: "#114B5C")
    )

    // MARK: Dracula
    static let dracula = Theme(
        id: "dracula",
        name: "Dracula",
        icon: "theatermask.and.paintbrush.fill",
        sidebarBackground: Color(hex: "#21222C"),
        listBackground: Color(hex: "#282A36"),
        detailBackground: Color(hex: "#282A36"),
        cardBackground: Color(hex: "#343746"),
        selectedCardBackground: Color(hex: "#44475A"),
        hoverBackground: Color(hex: "#343746"),
        searchBarBackground: Color(hex: "#343746"),
        accentPrimary: Color(hex: "#BD93F9"),
        accentSecondary: Color(hex: "#50FA7B"),
        textPrimary: Color(hex: "#F8F8F2"),
        textSecondary: Color(hex: "#BFBFBF"),
        textTertiary: Color(hex: "#6272A4"),
        textInverse: Color(hex: "#282A36"),
        border: Color(hex: "#44475A"),
        divider: Color(hex: "#343746"),
        unreadIndicator: Color(hex: "#FF79C6"),
        attachmentBackground: Color(hex: "#343746"),
        avatarRing: Color(hex: "#BD93F9"),
        destructive: Color(hex: "#FF5555"),
        buttonPrimary: Color(hex: "#BD93F9"),
        buttonSecondary: Color(hex: "#44475A"),
        inputBackground: Color(hex: "#282A36"),
        tagBackground: Color(hex: "#44475A")
    )

    // MARK: One Dark (Atom)
    static let oneDark = Theme(
        id: "one-dark",
        name: "One Dark",
        icon: "atom",
        sidebarBackground: Color(hex: "#21252B"),
        listBackground: Color(hex: "#282C34"),
        detailBackground: Color(hex: "#282C34"),
        cardBackground: Color(hex: "#2C313A"),
        selectedCardBackground: Color(hex: "#3E4451"),
        hoverBackground: Color(hex: "#2C313A"),
        searchBarBackground: Color(hex: "#2C313A"),
        accentPrimary: Color(hex: "#61AFEF"),
        accentSecondary: Color(hex: "#98C379"),
        textPrimary: Color(hex: "#ABB2BF"),
        textSecondary: Color(hex: "#848B98"),
        textTertiary: Color(hex: "#5C6370"),
        textInverse: Color(hex: "#282C34"),
        border: Color(hex: "#3E4451"),
        divider: Color(hex: "#2C313A"),
        unreadIndicator: Color(hex: "#61AFEF"),
        attachmentBackground: Color(hex: "#2C313A"),
        avatarRing: Color(hex: "#61AFEF"),
        destructive: Color(hex: "#E06C75"),
        buttonPrimary: Color(hex: "#61AFEF"),
        buttonSecondary: Color(hex: "#3E4451"),
        inputBackground: Color(hex: "#282C34"),
        tagBackground: Color(hex: "#3E4451")
    )

    // MARK: Catppuccin (Mocha) ✨ NEW
    static let catppuccin = Theme(
        id: "catppuccin",
        name: "Catppuccin",
        icon: "cup.and.saucer.fill",
        sidebarBackground: Color(hex: "#11111B"),
        listBackground: Color(hex: "#181825"),
        detailBackground: Color(hex: "#1E1E2E"),
        cardBackground: Color(hex: "#313244"),
        selectedCardBackground: Color(hex: "#45475A"),
        hoverBackground: Color(hex: "#313244"),
        searchBarBackground: Color(hex: "#313244"),
        accentPrimary: Color(hex: "#CBA6F7"),
        accentSecondary: Color(hex: "#A6E3A1"),
        textPrimary: Color(hex: "#CDD6F4"),
        textSecondary: Color(hex: "#A6ADC8"),
        textTertiary: Color(hex: "#6C7086"),
        textInverse: Color(hex: "#1E1E2E"),
        border: Color(hex: "#45475A"),
        divider: Color(hex: "#313244"),
        unreadIndicator: Color(hex: "#F38BA8"),
        attachmentBackground: Color(hex: "#313244"),
        avatarRing: Color(hex: "#CBA6F7"),
        destructive: Color(hex: "#F38BA8"),
        buttonPrimary: Color(hex: "#89B4FA"),
        buttonSecondary: Color(hex: "#45475A"),
        inputBackground: Color(hex: "#181825"),
        tagBackground: Color(hex: "#45475A")
    )

    // MARK: Tokyo Night ✨ NEW (remplace Xcode Dark)
    static let tokyoNight = Theme(
        id: "tokyo-night",
        name: "Tokyo Night",
        icon: "building.2.fill",
        sidebarBackground: Color(hex: "#16161E"),
        listBackground: Color(hex: "#1A1B26"),
        detailBackground: Color(hex: "#1A1B26"),
        cardBackground: Color(hex: "#24283B"),
        selectedCardBackground: Color(hex: "#292E42"),
        hoverBackground: Color(hex: "#24283B"),
        searchBarBackground: Color(hex: "#24283B"),
        accentPrimary: Color(hex: "#7AA2F7"),
        accentSecondary: Color(hex: "#9ECE6A"),
        textPrimary: Color(hex: "#C0CAF5"),
        textSecondary: Color(hex: "#A9B1D6"),
        textTertiary: Color(hex: "#565F89"),
        textInverse: Color(hex: "#1A1B26"),
        border: Color(hex: "#3B4261"),
        divider: Color(hex: "#292E42"),
        unreadIndicator: Color(hex: "#7DCFFF"),
        attachmentBackground: Color(hex: "#24283B"),
        avatarRing: Color(hex: "#BB9AF7"),
        destructive: Color(hex: "#F7768E"),
        buttonPrimary: Color(hex: "#7AA2F7"),
        buttonSecondary: Color(hex: "#3B4261"),
        inputBackground: Color(hex: "#1A1B26"),
        tagBackground: Color(hex: "#292E42")
    )

    // MARK: Forest ✨ NEW
    static let forest = Theme(
        id: "forest",
        name: "Forest",
        icon: "leaf.fill",
        sidebarBackground: Color(hex: "#0F1A10"),
        listBackground: Color(hex: "#142216"),
        detailBackground: Color(hex: "#182A1A"),
        cardBackground: Color(hex: "#1F3522"),
        selectedCardBackground: Color(hex: "#28422B"),
        hoverBackground: Color(hex: "#1F3522"),
        searchBarBackground: Color(hex: "#1F3522"),
        accentPrimary: Color(hex: "#7CB342"),
        accentSecondary: Color(hex: "#FFB74D"),
        textPrimary: Color(hex: "#E8F0E4"),
        textSecondary: Color(hex: "#9AAF8E"),
        textTertiary: Color(hex: "#5E7A52"),
        textInverse: Color(hex: "#0F1A10"),
        border: Color(hex: "#2A4A2E"),
        divider: Color(hex: "#1F3522"),
        unreadIndicator: Color(hex: "#7CB342"),
        attachmentBackground: Color(hex: "#1F3522"),
        avatarRing: Color(hex: "#7CB342"),
        destructive: Color(hex: "#EF5350"),
        buttonPrimary: Color(hex: "#558B2F"),
        buttonSecondary: Color(hex: "#2A4A2E"),
        inputBackground: Color(hex: "#142216"),
        tagBackground: Color(hex: "#28422B")
    )

    // ──────────────────────────────────────────────
    // MARK: - Light Themes
    // ──────────────────────────────────────────────

    // MARK: Light
    static let light = Theme(
        id: "light",
        name: "Light",
        icon: "sun.max.fill",
        sidebarBackground: Color(hex: "#F2F2F7"),
        listBackground: Color(hex: "#FFFFFF"),
        detailBackground: Color(hex: "#FFFFFF"),
        cardBackground: Color(hex: "#F8F8FA"),
        selectedCardBackground: Color(hex: "#E8E5F5"),
        hoverBackground: Color(hex: "#F2F2F7"),
        searchBarBackground: Color(hex: "#E5E5EA"),
        accentPrimary: Color(hex: "#5E4DB2"),
        accentSecondary: Color(hex: "#28A745"),
        textPrimary: Color(hex: "#1C1C1E"),
        textSecondary: Color(hex: "#6E6E73"),
        textTertiary: Color(hex: "#AEAEB2"),
        textInverse: Color(hex: "#FFFFFF"),
        border: Color(hex: "#D1D1D6"),
        divider: Color(hex: "#E5E5EA"),
        unreadIndicator: Color(hex: "#5E4DB2"),
        attachmentBackground: Color(hex: "#F2F2F7"),
        avatarRing: Color(hex: "#5E4DB2"),
        destructive: Color(hex: "#FF3B30"),
        buttonPrimary: Color(hex: "#5E4DB2"),
        buttonSecondary: Color(hex: "#E5E5EA"),
        inputBackground: Color(hex: "#F2F2F7"),
        tagBackground: Color(hex: "#E8E5F5")
    )

    // MARK: Paper (anciennement emerald)
    static let paper = Theme(
        id: "paper",
        name: "Paper",
        icon: "doc.plaintext",
        sidebarBackground: Color(hex: "#E8DFD0"),
        listBackground: Color(hex: "#F0E8DA"),
        detailBackground: Color(hex: "#F5EDE0"),
        cardBackground: Color(hex: "#EAE1D2"),
        selectedCardBackground: Color(hex: "#D9CEBB"),
        hoverBackground: Color(hex: "#E2D8C8"),
        searchBarBackground: Color(hex: "#E2D8C8"),
        accentPrimary: Color(hex: "#1B3A4B"),
        accentSecondary: Color(hex: "#D96A3B"),
        textPrimary: Color(hex: "#1C1917"),
        textSecondary: Color(hex: "#57534E"),
        textTertiary: Color(hex: "#A8A29E"),
        textInverse: Color(hex: "#F5EDE0"),
        border: Color(hex: "#D6CDB9"),
        divider: Color(hex: "#DDD4C4"),
        unreadIndicator: Color(hex: "#D96A3B"),
        attachmentBackground: Color(hex: "#E2D8C8"),
        avatarRing: Color(hex: "#1B3A4B"),
        destructive: Color(hex: "#C4432B"),
        buttonPrimary: Color(hex: "#1B3A4B"),
        buttonSecondary: Color(hex: "#D6CDB9"),
        inputBackground: Color(hex: "#F0E8DA"),
        tagBackground: Color(hex: "#D6CDB9")
    )

    // MARK: Violet (anciennement sunset)
    static let violet = Theme(
        id: "violet",
        name: "Violet",
        icon: "diamond.fill",
        sidebarBackground: Color(hex: "#5B3D9B"),
        listBackground: Color(hex: "#FFFFFF"),
        detailBackground: Color(hex: "#FFFFFF"),
        cardBackground: Color(hex: "#F7F5FC"),
        selectedCardBackground: Color(hex: "#EBE3F7"),
        hoverBackground: Color(hex: "#F0ECF7"),
        searchBarBackground: Color(hex: "#EDEBF2"),
        accentPrimary: Color(hex: "#6B4EAF"),
        accentSecondary: Color(hex: "#9B7ED8"),
        textPrimary: Color(hex: "#1A1A2E"),
        textSecondary: Color(hex: "#6B6B80"),
        textTertiary: Color(hex: "#A8A8B8"),
        textInverse: Color(hex: "#FFFFFF"),
        border: Color(hex: "#E0DCE8"),
        divider: Color(hex: "#E8E5F0"),
        unreadIndicator: Color(hex: "#6B4EAF"),
        attachmentBackground: Color(hex: "#F0ECF7"),
        avatarRing: Color(hex: "#6B4EAF"),
        destructive: Color(hex: "#EF4444"),
        buttonPrimary: Color(hex: "#6B4EAF"),
        buttonSecondary: Color(hex: "#E8E5F0"),
        inputBackground: Color(hex: "#F2F0F7"),
        tagBackground: Color(hex: "#EBE3F7")
    )

    // MARK: Mono
    static let mono = Theme(
        id: "mono",
        name: "Mono",
        icon: "circle.lefthalf.filled",
        sidebarBackground: Color(hex: "#1A1A1A"),
        listBackground: Color(hex: "#FFFFFF"),
        detailBackground: Color(hex: "#FAFAFA"),
        cardBackground: Color(hex: "#FFFFFF"),
        selectedCardBackground: Color(hex: "#F0F0F0"),
        hoverBackground: Color(hex: "#F5F5F5"),
        searchBarBackground: Color(hex: "#F0F0F0"),
        accentPrimary: Color(hex: "#1A1A1A"),
        accentSecondary: Color(hex: "#555555"),
        textPrimary: Color(hex: "#111111"),
        textSecondary: Color(hex: "#666666"),
        textTertiary: Color(hex: "#AAAAAA"),
        textInverse: Color(hex: "#FFFFFF"),
        border: Color(hex: "#E0E0E0"),
        divider: Color(hex: "#EBEBEB"),
        unreadIndicator: Color(hex: "#111111"),
        attachmentBackground: Color(hex: "#F5F5F5"),
        avatarRing: Color(hex: "#333333"),
        destructive: Color(hex: "#DC2626"),
        buttonPrimary: Color(hex: "#111111"),
        buttonSecondary: Color(hex: "#E5E5E5"),
        inputBackground: Color(hex: "#F5F5F5"),
        tagBackground: Color(hex: "#F0F0F0")
    )

    // MARK: Ivory ✨ NEW – light chaud, crème doré
    static let ivory = Theme(
        id: "ivory",
        name: "Ivory",
        icon: "sun.and.horizon.fill",
        sidebarBackground: Color(hex: "#F5EDE0"),
        listBackground: Color(hex: "#FFFBF5"),
        detailBackground: Color(hex: "#FFF9F0"),
        cardBackground: Color(hex: "#FFF5E8"),
        selectedCardBackground: Color(hex: "#F0E0C8"),
        hoverBackground: Color(hex: "#F7EDDB"),
        searchBarBackground: Color(hex: "#F0E5D4"),
        accentPrimary: Color(hex: "#B8621B"),
        accentSecondary: Color(hex: "#2E7D6F"),
        textPrimary: Color(hex: "#2C2416"),
        textSecondary: Color(hex: "#6B5D4E"),
        textTertiary: Color(hex: "#B0A494"),
        textInverse: Color(hex: "#FFFBF5"),
        border: Color(hex: "#E5D9C8"),
        divider: Color(hex: "#EDE2D2"),
        unreadIndicator: Color(hex: "#B8621B"),
        attachmentBackground: Color(hex: "#F7EDDB"),
        avatarRing: Color(hex: "#B8621B"),
        destructive: Color(hex: "#C0392B"),
        buttonPrimary: Color(hex: "#B8621B"),
        buttonSecondary: Color(hex: "#E5D9C8"),
        inputBackground: Color(hex: "#FFF8F0"),
        tagBackground: Color(hex: "#F0E0C8")
    )
}
