import SwiftUI

extension Theme {
    // MARK: - Midnight (GitHub Dark Mode)
    static let midnight = Theme(
        id: "midnight",
        name: "Midnight",
        icon: "moon.stars.fill",
        sidebarBackground: Color(hex: "#010409"),
        listBackground: Color(hex: "#0D1117"),
        detailBackground: Color(hex: "#0D1117"),
        cardBackground: Color(hex: "#161B22"),
        selectedCardBackground: Color(hex: "#1F2937"),
        hoverBackground: Color(hex: "#161B22"),
        searchBarBackground: Color(hex: "#161B22"),
        accentPrimary: Color(hex: "#58A6FF"),
        accentSecondary: Color(hex: "#3FB950"),
        textPrimary: Color(hex: "#E6EDF3"),
        textSecondary: Color(hex: "#8B949E"),
        textTertiary: Color(hex: "#484F58"),
        textInverse: Color(hex: "#FFFFFF"),
        border: Color(hex: "#30363D"),
        divider: Color(hex: "#21262D"),
        unreadIndicator: Color(hex: "#58A6FF"),
        attachmentBackground: Color(hex: "#161B22"),
        avatarRing: Color(hex: "#58A6FF"),
        destructive: Color(hex: "#F85149"),
        buttonPrimary: Color(hex: "#238636"),
        buttonSecondary: Color(hex: "#21262D"),
        inputBackground: Color(hex: "#0D1117"),
        tagBackground: Color(hex: "#1F2937")
    )

    // MARK: - Ocean
    static let ocean = Theme(
        id: "ocean",
        name: "Ocean",
        icon: "water.waves",
        sidebarBackground: Color(hex: "#0A1628"),
        listBackground: Color(hex: "#0F1D30"),
        detailBackground: Color(hex: "#132238"),
        cardBackground: Color(hex: "#1A2D45"),
        selectedCardBackground: Color(hex: "#203852"),
        hoverBackground: Color(hex: "#1A2D45"),
        searchBarBackground: Color(hex: "#1A2D45"),
        accentPrimary: Color(hex: "#0A84FF"),
        accentSecondary: Color(hex: "#30D158"),
        textPrimary: Color(hex: "#FFFFFF"),
        textSecondary: Color(hex: "#7B8FA0"),
        textTertiary: Color(hex: "#4A5D6E"),
        textInverse: Color(hex: "#FFFFFF"),
        border: Color(hex: "#1E3550"),
        divider: Color(hex: "#1A2D45"),
        unreadIndicator: Color(hex: "#0A84FF"),
        attachmentBackground: Color(hex: "#1A2D45"),
        avatarRing: Color(hex: "#0A84FF"),
        destructive: Color(hex: "#FF453A"),
        buttonPrimary: Color(hex: "#0A84FF"),
        buttonSecondary: Color(hex: "#1E3550"),
        inputBackground: Color(hex: "#1A2D45"),
        tagBackground: Color(hex: "#203852")
    )

    // MARK: - Charcoal
    static let charcoal = Theme(
        id: "charcoal",
        name: "Charcoal",
        icon: "circle.lefthalf.filled",
        sidebarBackground: Color(hex: "#1A1A1A"),
        listBackground: Color(hex: "#212121"),
        detailBackground: Color(hex: "#262626"),
        cardBackground: Color(hex: "#2E2E2E"),
        selectedCardBackground: Color(hex: "#383838"),
        hoverBackground: Color(hex: "#2E2E2E"),
        searchBarBackground: Color(hex: "#2E2E2E"),
        accentPrimary: Color(hex: "#FF9F0A"),
        accentSecondary: Color(hex: "#30D158"),
        textPrimary: Color(hex: "#F5F5F5"),
        textSecondary: Color(hex: "#999999"),
        textTertiary: Color(hex: "#666666"),
        textInverse: Color(hex: "#1A1A1A"),
        border: Color(hex: "#3A3A3A"),
        divider: Color(hex: "#333333"),
        unreadIndicator: Color(hex: "#FF9F0A"),
        attachmentBackground: Color(hex: "#2E2E2E"),
        avatarRing: Color(hex: "#FF9F0A"),
        destructive: Color(hex: "#FF453A"),
        buttonPrimary: Color(hex: "#FF9F0A"),
        buttonSecondary: Color(hex: "#3A3A3A"),
        inputBackground: Color(hex: "#2E2E2E"),
        tagBackground: Color(hex: "#383838")
    )

    // MARK: - Nord
    static let nord = Theme(
        id: "nord",
        name: "Nord",
        icon: "snowflake",
        sidebarBackground: Color(hex: "#2E3440"),
        listBackground: Color(hex: "#3B4252"),
        detailBackground: Color(hex: "#434C5E"),
        cardBackground: Color(hex: "#4C566A"),
        selectedCardBackground: Color(hex: "#5E6A82"),
        hoverBackground: Color(hex: "#4C566A"),
        searchBarBackground: Color(hex: "#4C566A"),
        accentPrimary: Color(hex: "#88C0D0"),
        accentSecondary: Color(hex: "#A3BE8C"),
        textPrimary: Color(hex: "#ECEFF4"),
        textSecondary: Color(hex: "#D8DEE9"),
        textTertiary: Color(hex: "#9BA3B0"),
        textInverse: Color(hex: "#2E3440"),
        border: Color(hex: "#5E6A82"),
        divider: Color(hex: "#4C566A"),
        unreadIndicator: Color(hex: "#88C0D0"),
        attachmentBackground: Color(hex: "#4C566A"),
        avatarRing: Color(hex: "#88C0D0"),
        destructive: Color(hex: "#BF616A"),
        buttonPrimary: Color(hex: "#88C0D0"),
        buttonSecondary: Color(hex: "#5E6A82"),
        inputBackground: Color(hex: "#4C566A"),
        tagBackground: Color(hex: "#5E6A82")
    )

    // MARK: - Rosé
    static let rose = Theme(
        id: "rose",
        name: "Rosé",
        icon: "heart.fill",
        sidebarBackground: Color(hex: "#1A1118"),
        listBackground: Color(hex: "#211620"),
        detailBackground: Color(hex: "#281B26"),
        cardBackground: Color(hex: "#32222F"),
        selectedCardBackground: Color(hex: "#3E2C3A"),
        hoverBackground: Color(hex: "#32222F"),
        searchBarBackground: Color(hex: "#32222F"),
        accentPrimary: Color(hex: "#E8A0BF"),
        accentSecondary: Color(hex: "#BA68C8"),
        textPrimary: Color(hex: "#F8E8F0"),
        textSecondary: Color(hex: "#B89AAE"),
        textTertiary: Color(hex: "#7A5A6E"),
        textInverse: Color(hex: "#1A1118"),
        border: Color(hex: "#3E2C3A"),
        divider: Color(hex: "#32222F"),
        unreadIndicator: Color(hex: "#E8A0BF"),
        attachmentBackground: Color(hex: "#32222F"),
        avatarRing: Color(hex: "#E8A0BF"),
        destructive: Color(hex: "#FF6B8A"),
        buttonPrimary: Color(hex: "#E8A0BF"),
        buttonSecondary: Color(hex: "#3E2C3A"),
        inputBackground: Color(hex: "#32222F"),
        tagBackground: Color(hex: "#3E2C3A")
    )

    // MARK: - Light
    static let light = Theme(
        id: "light",
        name: "Light",
        icon: "sun.max.fill",
        sidebarBackground: Color(hex: "#F2F2F7"),
        listBackground: Color(hex: "#FFFFFF"),
        detailBackground: Color(hex: "#FFFFFF"),
        cardBackground: Color(hex: "#F8F8FA"),
        selectedCardBackground: Color(hex: "#E8E5F5"),
        hoverBackground: Color(hex: "#F2F2F7"),
        searchBarBackground: Color(hex: "#E5E5EA"),
        accentPrimary: Color(hex: "#5E4DB2"),
        accentSecondary: Color(hex: "#28A745"),
        textPrimary: Color(hex: "#1C1C1E"),
        textSecondary: Color(hex: "#6E6E73"),
        textTertiary: Color(hex: "#AEAEB2"),
        textInverse: Color(hex: "#FFFFFF"),
        border: Color(hex: "#D1D1D6"),
        divider: Color(hex: "#E5E5EA"),
        unreadIndicator: Color(hex: "#5E4DB2"),
        attachmentBackground: Color(hex: "#F2F2F7"),
        avatarRing: Color(hex: "#5E4DB2"),
        destructive: Color(hex: "#FF3B30"),
        buttonPrimary: Color(hex: "#5E4DB2"),
        buttonSecondary: Color(hex: "#E5E5EA"),
        inputBackground: Color(hex: "#F2F2F7"),
        tagBackground: Color(hex: "#E8E5F5")
    )
}
