import SwiftUI

extension Theme {
    // MARK: - Midnight (GitHub Dark Mode)
    static let midnight = Theme(
        id: "midnight",
        name: "Midnight",
        icon: "moon.stars.fill",
        sidebarBackground: Color(hex: "#010409"),
        listBackground: Color(hex: "#0D1117"),
        detailBackground: Color(hex: "#0D1117"),
        cardBackground: Color(hex: "#161B22"),
        selectedCardBackground: Color(hex: "#1F2937"),
        hoverBackground: Color(hex: "#161B22"),
        searchBarBackground: Color(hex: "#161B22"),
        accentPrimary: Color(hex: "#58A6FF"),
        accentSecondary: Color(hex: "#3FB950"),
        textPrimary: Color(hex: "#E6EDF3"),
        textSecondary: Color(hex: "#8B949E"),
        textTertiary: Color(hex: "#484F58"),
        textInverse: Color(hex: "#FFFFFF"),
        border: Color(hex: "#30363D"),
        divider: Color(hex: "#21262D"),
        unreadIndicator: Color(hex: "#58A6FF"),
        attachmentBackground: Color(hex: "#161B22"),
        avatarRing: Color(hex: "#58A6FF"),
        destructive: Color(hex: "#F85149"),
        buttonPrimary: Color(hex: "#238636"),
        buttonSecondary: Color(hex: "#21262D"),
        inputBackground: Color(hex: "#0D1117"),
        tagBackground: Color(hex: "#1F2937")
    )

    // MARK: - Ocean
    static let ocean = Theme(
        id: "ocean",
        name: "Ocean",
        icon: "water.waves",
        sidebarBackground: Color(hex: "#0A1628"),
        listBackground: Color(hex: "#0F1D30"),
        detailBackground: Color(hex: "#132238"),
        cardBackground: Color(hex: "#1A2D45"),
        selectedCardBackground: Color(hex: "#203852"),
        hoverBackground: Color(hex: "#1A2D45"),
        searchBarBackground: Color(hex: "#1A2D45"),
        accentPrimary: Color(hex: "#0A84FF"),
        accentSecondary: Color(hex: "#30D158"),
        textPrimary: Color(hex: "#FFFFFF"),
        textSecondary: Color(hex: "#7B8FA0"),
        textTertiary: Color(hex: "#4A5D6E"),
        textInverse: Color(hex: "#FFFFFF"),
        border: Color(hex: "#1E3550"),
        divider: Color(hex: "#1A2D45"),
        unreadIndicator: Color(hex: "#0A84FF"),
        attachmentBackground: Color(hex: "#1A2D45"),
        avatarRing: Color(hex: "#0A84FF"),
        destructive: Color(hex: "#FF453A"),
        buttonPrimary: Color(hex: "#0A84FF"),
        buttonSecondary: Color(hex: "#1E3550"),
        inputBackground: Color(hex: "#1A2D45"),
        tagBackground: Color(hex: "#203852")
    )

    // MARK: - Serif
    static let serif = Theme(
        id: "serif",
        name: "Serif",
        icon: "book.fill",
        sidebarBackground: Color(hex: "#181C26"),
        listBackground: Color(hex: "#1C2230"),
        detailBackground: Color(hex: "#202636"),
        cardBackground: Color(hex: "#272D3C"),
        selectedCardBackground: Color(hex: "#303848"),
        hoverBackground: Color(hex: "#2A3040"),
        searchBarBackground: Color(hex: "#272D3C"),
        accentPrimary: Color(hex: "#E8736D"),
        accentSecondary: Color(hex: "#6E88E0"),
        textPrimary: Color(hex: "#E6E2EA"),
        textSecondary: Color(hex: "#8A8694"),
        textTertiary: Color(hex: "#56525E"),
        textInverse: Color(hex: "#1C2230"),
        border: Color(hex: "#343A4A"),
        divider: Color(hex: "#282E3C"),
        unreadIndicator: Color(hex: "#6E88E0"),
        attachmentBackground: Color(hex: "#272D3C"),
        avatarRing: Color(hex: "#E8736D"),
        destructive: Color(hex: "#E8736D"),
        buttonPrimary: Color(hex: "#6E88E0"),
        buttonSecondary: Color(hex: "#343A4A"),
        inputBackground: Color(hex: "#1C2230"),
        tagBackground: Color(hex: "#303848")
    )

    // MARK: - Nord
    static let nord = Theme(
        id: "nord",
        name: "Nord",
        icon: "snowflake",
        sidebarBackground: Color(hex: "#2E3440"),
        listBackground: Color(hex: "#3B4252"),
        detailBackground: Color(hex: "#434C5E"),
        cardBackground: Color(hex: "#4C566A"),
        selectedCardBackground: Color(hex: "#5E6A82"),
        hoverBackground: Color(hex: "#4C566A"),
        searchBarBackground: Color(hex: "#4C566A"),
        accentPrimary: Color(hex: "#88C0D0"),
        accentSecondary: Color(hex: "#A3BE8C"),
        textPrimary: Color(hex: "#ECEFF4"),
        textSecondary: Color(hex: "#D8DEE9"),
        textTertiary: Color(hex: "#9BA3B0"),
        textInverse: Color(hex: "#2E3440"),
        border: Color(hex: "#5E6A82"),
        divider: Color(hex: "#4C566A"),
        unreadIndicator: Color(hex: "#88C0D0"),
        attachmentBackground: Color(hex: "#4C566A"),
        avatarRing: Color(hex: "#88C0D0"),
        destructive: Color(hex: "#BF616A"),
        buttonPrimary: Color(hex: "#88C0D0"),
        buttonSecondary: Color(hex: "#5E6A82"),
        inputBackground: Color(hex: "#4C566A"),
        tagBackground: Color(hex: "#5E6A82")
    )

    // MARK: - Rosé
    static let rose = Theme(
        id: "rose",
        name: "Rosé",
        icon: "heart.fill",
        sidebarBackground: Color(hex: "#1A1118"),
        listBackground: Color(hex: "#211620"),
        detailBackground: Color(hex: "#281B26"),
        cardBackground: Color(hex: "#32222F"),
        selectedCardBackground: Color(hex: "#3E2C3A"),
        hoverBackground: Color(hex: "#32222F"),
        searchBarBackground: Color(hex: "#32222F"),
        accentPrimary: Color(hex: "#E8A0BF"),
        accentSecondary: Color(hex: "#BA68C8"),
        textPrimary: Color(hex: "#F8E8F0"),
        textSecondary: Color(hex: "#B89AAE"),
        textTertiary: Color(hex: "#7A5A6E"),
        textInverse: Color(hex: "#1A1118"),
        border: Color(hex: "#3E2C3A"),
        divider: Color(hex: "#32222F"),
        unreadIndicator: Color(hex: "#E8A0BF"),
        attachmentBackground: Color(hex: "#32222F"),
        avatarRing: Color(hex: "#E8A0BF"),
        destructive: Color(hex: "#FF6B8A"),
        buttonPrimary: Color(hex: "#E8A0BF"),
        buttonSecondary: Color(hex: "#3E2C3A"),
        inputBackground: Color(hex: "#32222F"),
        tagBackground: Color(hex: "#3E2C3A")
    )

    // MARK: - Xcode Dark
    static let xcodeDark = Theme(
        id: "xcode-dark",
        name: "Xcode Dark",
        icon: "hammer.fill",
        sidebarBackground: Color(hex: "#1E1E1E"),
        listBackground: Color(hex: "#232323"),
        detailBackground: Color(hex: "#292A30"),
        cardBackground: Color(hex: "#2F3037"),
        selectedCardBackground: Color(hex: "#3F4450"),
        hoverBackground: Color(hex: "#2F3037"),
        searchBarBackground: Color(hex: "#2F3037"),
        accentPrimary: Color(hex: "#0A7AFF"),
        accentSecondary: Color(hex: "#67B7A4"),
        textPrimary: Color(hex: "#DFDFE0"),
        textSecondary: Color(hex: "#8E8E93"),
        textTertiary: Color(hex: "#5A5A5E"),
        textInverse: Color(hex: "#FFFFFF"),
        border: Color(hex: "#3C3C3E"),
        divider: Color(hex: "#38383A"),
        unreadIndicator: Color(hex: "#0A7AFF"),
        attachmentBackground: Color(hex: "#2F3037"),
        avatarRing: Color(hex: "#0A7AFF"),
        destructive: Color(hex: "#FF6961"),
        buttonPrimary: Color(hex: "#0A7AFF"),
        buttonSecondary: Color(hex: "#3C3C3E"),
        inputBackground: Color(hex: "#1E1E1E"),
        tagBackground: Color(hex: "#3F4450")
    )

    // MARK: - Papier
    static let emerald = Theme(
        id: "emerald",
        name: "Papier",
        icon: "doc.plaintext",
        sidebarBackground: Color(hex: "#E8DFD0"),
        listBackground: Color(hex: "#F0E8DA"),
        detailBackground: Color(hex: "#F5EDE0"),
        cardBackground: Color(hex: "#EAE1D2"),
        selectedCardBackground: Color(hex: "#D9CEBB"),
        hoverBackground: Color(hex: "#E2D8C8"),
        searchBarBackground: Color(hex: "#E2D8C8"),
        accentPrimary: Color(hex: "#1B3A4B"),
        accentSecondary: Color(hex: "#D96A3B"),
        textPrimary: Color(hex: "#1C1917"),
        textSecondary: Color(hex: "#57534E"),
        textTertiary: Color(hex: "#A8A29E"),
        textInverse: Color(hex: "#F5EDE0"),
        border: Color(hex: "#D6CDB9"),
        divider: Color(hex: "#DDD4C4"),
        unreadIndicator: Color(hex: "#D96A3B"),
        attachmentBackground: Color(hex: "#E2D8C8"),
        avatarRing: Color(hex: "#1B3A4B"),
        destructive: Color(hex: "#C4432B"),
        buttonPrimary: Color(hex: "#1B3A4B"),
        buttonSecondary: Color(hex: "#D6CDB9"),
        inputBackground: Color(hex: "#F0E8DA"),
        tagBackground: Color(hex: "#D6CDB9")
    )

    // MARK: - Solarized Dark
    static let solarizedDark = Theme(
        id: "solarized-dark",
        name: "Solarized",
        icon: "sun.haze.fill",
        sidebarBackground: Color(hex: "#002129"),
        listBackground: Color(hex: "#002B36"),
        detailBackground: Color(hex: "#073642"),
        cardBackground: Color(hex: "#0A4050"),
        selectedCardBackground: Color(hex: "#114B5C"),
        hoverBackground: Color(hex: "#0A4050"),
        searchBarBackground: Color(hex: "#0A4050"),
        accentPrimary: Color(hex: "#268BD2"),
        accentSecondary: Color(hex: "#2AA198"),
        textPrimary: Color(hex: "#FDF6E3"),
        textSecondary: Color(hex: "#93A1A1"),
        textTertiary: Color(hex: "#657B83"),
        textInverse: Color(hex: "#002B36"),
        border: Color(hex: "#114B5C"),
        divider: Color(hex: "#073642"),
        unreadIndicator: Color(hex: "#268BD2"),
        attachmentBackground: Color(hex: "#0A4050"),
        avatarRing: Color(hex: "#268BD2"),
        destructive: Color(hex: "#DC322F"),
        buttonPrimary: Color(hex: "#268BD2"),
        buttonSecondary: Color(hex: "#114B5C"),
        inputBackground: Color(hex: "#002B36"),
        tagBackground: Color(hex: "#114B5C")
    )

    // MARK: - Dracula
    static let dracula = Theme(
        id: "dracula",
        name: "Dracula",
        icon: "theatermask.and.paintbrush.fill",
        sidebarBackground: Color(hex: "#21222C"),
        listBackground: Color(hex: "#282A36"),
        detailBackground: Color(hex: "#282A36"),
        cardBackground: Color(hex: "#343746"),
        selectedCardBackground: Color(hex: "#44475A"),
        hoverBackground: Color(hex: "#343746"),
        searchBarBackground: Color(hex: "#343746"),
        accentPrimary: Color(hex: "#BD93F9"),
        accentSecondary: Color(hex: "#50FA7B"),
        textPrimary: Color(hex: "#F8F8F2"),
        textSecondary: Color(hex: "#BFBFBF"),
        textTertiary: Color(hex: "#6272A4"),
        textInverse: Color(hex: "#282A36"),
        border: Color(hex: "#44475A"),
        divider: Color(hex: "#343746"),
        unreadIndicator: Color(hex: "#FF79C6"),
        attachmentBackground: Color(hex: "#343746"),
        avatarRing: Color(hex: "#BD93F9"),
        destructive: Color(hex: "#FF5555"),
        buttonPrimary: Color(hex: "#BD93F9"),
        buttonSecondary: Color(hex: "#44475A"),
        inputBackground: Color(hex: "#282A36"),
        tagBackground: Color(hex: "#44475A")
    )

    // MARK: - One Dark (Atom)
    static let oneDark = Theme(
        id: "one-dark",
        name: "One Dark",
        icon: "atom",
        sidebarBackground: Color(hex: "#21252B"),
        listBackground: Color(hex: "#282C34"),
        detailBackground: Color(hex: "#282C34"),
        cardBackground: Color(hex: "#2C313A"),
        selectedCardBackground: Color(hex: "#3E4451"),
        hoverBackground: Color(hex: "#2C313A"),
        searchBarBackground: Color(hex: "#2C313A"),
        accentPrimary: Color(hex: "#61AFEF"),
        accentSecondary: Color(hex: "#98C379"),
        textPrimary: Color(hex: "#ABB2BF"),
        textSecondary: Color(hex: "#848B98"),
        textTertiary: Color(hex: "#5C6370"),
        textInverse: Color(hex: "#282C34"),
        border: Color(hex: "#3E4451"),
        divider: Color(hex: "#2C313A"),
        unreadIndicator: Color(hex: "#61AFEF"),
        attachmentBackground: Color(hex: "#2C313A"),
        avatarRing: Color(hex: "#61AFEF"),
        destructive: Color(hex: "#E06C75"),
        buttonPrimary: Color(hex: "#61AFEF"),
        buttonSecondary: Color(hex: "#3E4451"),
        inputBackground: Color(hex: "#282C34"),
        tagBackground: Color(hex: "#3E4451")
    )

    // MARK: - Sunset
    static let sunset = Theme(
        id: "sunset",
        name: "Sunset",
        icon: "sunset.fill",
        sidebarBackground: Color(hex: "#1A0F0A"),
        listBackground: Color(hex: "#211510"),
        detailBackground: Color(hex: "#2A1A14"),
        cardBackground: Color(hex: "#35221A"),
        selectedCardBackground: Color(hex: "#422C22"),
        hoverBackground: Color(hex: "#35221A"),
        searchBarBackground: Color(hex: "#35221A"),
        accentPrimary: Color(hex: "#FB923C"),
        accentSecondary: Color(hex: "#F472B6"),
        textPrimary: Color(hex: "#FFF7ED"),
        textSecondary: Color(hex: "#B89A82"),
        textTertiary: Color(hex: "#7A5F4A"),
        textInverse: Color(hex: "#1A0F0A"),
        border: Color(hex: "#422C22"),
        divider: Color(hex: "#35221A"),
        unreadIndicator: Color(hex: "#FB923C"),
        attachmentBackground: Color(hex: "#35221A"),
        avatarRing: Color(hex: "#FB923C"),
        destructive: Color(hex: "#EF4444"),
        buttonPrimary: Color(hex: "#F97316"),
        buttonSecondary: Color(hex: "#422C22"),
        inputBackground: Color(hex: "#211510"),
        tagBackground: Color(hex: "#422C22")
    )

    // MARK: - Light
    static let light = Theme(
        id: "light",
        name: "Light",
        icon: "sun.max.fill",
        sidebarBackground: Color(hex: "#F2F2F7"),
        listBackground: Color(hex: "#FFFFFF"),
        detailBackground: Color(hex: "#FFFFFF"),
        cardBackground: Color(hex: "#F8F8FA"),
        selectedCardBackground: Color(hex: "#E8E5F5"),
        hoverBackground: Color(hex: "#F2F2F7"),
        searchBarBackground: Color(hex: "#E5E5EA"),
        accentPrimary: Color(hex: "#5E4DB2"),
        accentSecondary: Color(hex: "#28A745"),
        textPrimary: Color(hex: "#1C1C1E"),
        textSecondary: Color(hex: "#6E6E73"),
        textTertiary: Color(hex: "#AEAEB2"),
        textInverse: Color(hex: "#FFFFFF"),
        border: Color(hex: "#D1D1D6"),
        divider: Color(hex: "#E5E5EA"),
        unreadIndicator: Color(hex: "#5E4DB2"),
        attachmentBackground: Color(hex: "#F2F2F7"),
        avatarRing: Color(hex: "#5E4DB2"),
        destructive: Color(hex: "#FF3B30"),
        buttonPrimary: Color(hex: "#5E4DB2"),
        buttonSecondary: Color(hex: "#E5E5EA"),
        inputBackground: Color(hex: "#F2F2F7"),
        tagBackground: Color(hex: "#E8E5F5")
    )
}
