import Foundation
#if canImport(FoundationModels)
import FoundationModels
#endif

@MainActor
final class SummaryService {
    static let shared = SummaryService()

    private static let maxCacheSize = 200

    var accountID: String = "" {
        didSet {
            if oldValue != accountID {
                cache.removeAll()
                aiGenerated.removeAll()
            }
        }
    }

    private var cache: [String: String] = [:]
    /// Tracks which summaries were generated by Apple Intelligence vs fallback.
    private var aiGenerated: Set<String> = []

    private init() {}

    func cachedSummary(for email: Email) -> String? {
        guard let key = cacheKey(for: email) else { return nil }
        return cache[key]
    }

    func isAIGenerated(for email: Email) -> Bool {
        guard let key = cacheKey(for: email) else { return false }
        return aiGenerated.contains(key)
    }

    func summary(for email: Email) -> AsyncStream<String> {
        AsyncStream { continuation in
            let task = Task { @MainActor in
                if let key = cacheKey(for: email), let cached = cache[key] {
                    continuation.yield(cached)
                    continuation.finish()
                    return
                }

                if #available(macOS 26.0, *) {
                    #if canImport(FoundationModels)
                    await generateWithFoundationModels(email: email, continuation: continuation)
                    #else
                    yieldFallback(email: email, continuation: continuation)
                    #endif
                } else {
                    yieldFallback(email: email, continuation: continuation)
                }
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

    #if canImport(FoundationModels)
    @available(macOS 26.0, *)
    private func generateWithFoundationModels(email: Email, continuation: AsyncStream<String>.Continuation) async {
        do {
            let instructions = Instructions("""
            You are an email assistant inside a macOS email client. \
            The user is hovering over an email and wants a quick glanceable summary. \
            Rules:
            - Write 2-3 short sentences max.
            - Lead with the key intent or action requested, not a description of the email.
            - If there's a deadline, date, amount, or link, mention it.
            - If the email is a newsletter/promo, say what it's about in one line.
            - If it's a reply thread, focus on the latest message only.
            - Never start with "This email..." or "The sender...". Be direct.
            - Use the same language as the email body.
            - Strip any signature, disclaimer or legal notice from consideration.
            """)
            let session = LanguageModelSession(instructions: instructions)

            var context = "From: \(email.sender.name)"
            if !email.recipients.isEmpty {
                let to = email.recipients.prefix(3).map(\.name).joined(separator: ", ")
                context += "\nTo: \(to)"
            }
            context += "\nSubject: \(email.subject)"
            context += "\nDate: \(email.date.formatted(date: .abbreviated, time: .shortened))"
            if email.hasAttachments {
                let names = email.attachments.prefix(3).map(\.name).joined(separator: ", ")
                context += "\nAttachments: \(names)"
            }

            let body = cleanedPreview(from: email)
            let prompt = """
            \(context)

            \(body)
            """

            var accumulated = ""
            let response = session.streamResponse(to: prompt)
            for try await snapshot in response {
                accumulated = snapshot.content
                continuation.yield(accumulated)
            }

            if let key = cacheKey(for: email) {
                cache[key] = accumulated
                aiGenerated.insert(key)
                trimCacheIfNeeded()
            }
            continuation.finish()
        } catch {
            yieldFallback(email: email, continuation: continuation)
        }
    }
    #endif

    private func yieldFallback(email: Email, continuation: AsyncStream<String>.Continuation) {
        let fallback = cleanedPreview(from: email)
        if let key = cacheKey(for: email) {
            cache[key] = fallback
            trimCacheIfNeeded()
        }
        continuation.yield(fallback)
        continuation.finish()
    }

    private func cleanedPreview(from email: Email) -> String {
        let text = email.body.isEmpty ? email.preview : email.body
        return text.cleanedForAI()
    }

    private func cacheKey(for email: Email) -> String? {
        email.gmailMessageID ?? email.id.uuidString
    }

    private func trimCacheIfNeeded() {
        if cache.count > Self.maxCacheSize {
            cache.removeAll()
            aiGenerated.removeAll()
        }
    }
}
